### ISSUE TITLE
ERROR: Cannot find key: 

### ISSUE THREAD

**Issue by chang-zy** [hrbigelow/transformer-aiayn#1]
--cache_dir Usage: data.py <command>   available commands:    save_token_info  For detailed information on this command, run:   data.py --help

I'm using colab, and this error appeared, I hope someone could help me.

**Comment by hrbigelow** [comment]
Hi Cool-CoCoder,

Ahh sorry for the problem.  You are the first to try out this repo, it is still under development.  I will update the README since it is out of date.

**Comment by hrbigelow** [comment]
Hi Cool-CoCoder,

I've updated the README and included a Colab file.  Please let me know if it is a bit easier!

Best,

Henry
